name: MLflow Workflow

on:
  push:
    branches:
      - main

jobs:
  mlflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: make install

    - name: Run MLflow Script
      run: make run
      working-directory: .

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mlflow-artifacts
        path: mlruns
